//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToanThangEdu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentsCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentsCategory()
        {
            this.DocumentItems = new HashSet<DocumentItem>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> RootId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentItem> DocumentItems { get; set; }
    }
}
