//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToanThangEdu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentItem
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string DocumentContent { get; set; }
        public string DocumentURL { get; set; }
        public Nullable<long> CategoryId { get; set; }
    
        public virtual DocumentsCategory DocumentsCategory { get; set; }
    }
}
