//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToanThangEdu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudierInSchedule
    {
        public long Id { get; set; }
        public Nullable<int> SubjectScheduleId { get; set; }
        public Nullable<long> StudierId { get; set; }
    
        public virtual SubjectSchedule SubjectSchedule { get; set; }
    }
}
